#!/bin/bash

#This is chapter 27 example 

TITLE="Systeme Information Report for $HOSTNAME"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

MIN_VAL=1
MAX_VAL=100

INT=50

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
	if [[ "$INT" -ge "$MIN_VAL" && "$INT" -le "$MAX_VAL" ]]; then
		echo "$INT is within $MIN_VAL to $MAX_VAL."
	else 
		echo "$INT is out of range"	
	fi
else
	echo "INT is not an integer/">&2
	exit 1
fi

